name: Release

on:
  push:
    branches:
      - ci_test
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install build dependencies
        run: pip install -U setuptools wheel build
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Lint
        run: mypy smartquery
      - name: Test
        run: pytest tests
      - name: Build
        run: python -m build .
      - name: Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
          skip_existing: true
